INSERT INTO products (item_id, pr0duct_name, department_name, price, stock_quantity) VALUES (1,'Pencil','Office', 1.97, 100);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (2, 'Pen','Office',	4.97,100);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (3,'Notebook','Office',21.38,100);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (4,'Bookbag','School',9.88,	50);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (5,'Eraser','School',2.17,70);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (6,'Ruler','All departments',1.97,65);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (7,'Sharpener','School',1.48,100);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (8,'Glue','School',	4.41 ,55);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (9,'Crayon','School', 6.99, 45);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (10,'Highlighter','Office',	6.88,45);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (11, 'Tape','All departments',3.42,100);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (12, 'Sticker','School',1.2,50);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (13,'Lunch Box','School',11.99, 50);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (14,'Color Paper','School',12.38,100);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (15,'Folder','Office',13.12,60);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (16,'Binder','Office',15.99,60);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (17,'Erase Board','Office',	17.96,30);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (18,'Marker','Office',2.38,70);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (19,'Calculator','Office',5.09,50 );
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES (20,'Scissors','All departments',2.23,90);